### PR TITLE
Fix Swagger Docs to allow for codegeneration

### LINKED ISSUE #207: API docs at runfission.com generate malformed curl commands
>I tried running the `PUT /dns/{cid}` command from the Swagger API but got an error due to >malformed URL. This is the `curl` command that the Web UI generated:
>
```
curl -X PUT "https://"https://runfission.com"/dns/QmaYSP6h3AvqKCrsS9hvV6Zp7ZoKQTchJ737ezXxcNJj31" -H  "accept: text/plain;charset=utf-8"
```
>
>At the top of the page it says `[ Base URL: "https://runfission.com" ]`, so that's likely the issue.
>
>I fixed the URL and ran it from the command-line and it worked \o/

_Originally posted by @agentofuser in https://github.com/fission-suite/cli/issues/9#issuecomment-554090623_

### PR DESCRIPTION
**Pull request by bechurch**
## Summary

This PR fixes/implements the following **bugs/features**

* [x] Host being rendered with quotes
* [x] Host being rendered with scheme
* [x] OpenAPI refs containing spaces
* [x] Removes an invalid/redundant file upload param specification

Fixing these makes our openapi spec valid again

## Closing issues

closes #207

## After Merge
* [ ] Does this change invalidate any docs or tutorials? _If so ensure the changes needed are either made or recorded_
* [ ] Does this change require a release to be made? Is so please create and deploy the release

### CODE REVIEW

File: library/Fission/Internal/UTF8.hs [hunk 1]
```diff
@@ -55,6 +57,10 @@ stripN n = Text.dropEnd i . Text.drop i
     i :: Int
     i = fromIntegral n
 
+-- | Helper for showing nytestring without quotes
+stripQuotes :: Char8.ByteString -> [Char]
```
Comment (dholms) [inline library/Fission/Internal/UTF8.hs]: This is probably fine as is. I would either
- rename this something that follows the pattern `stripN...` since this doesn't actually "strip quotes" it strips one char on each side
- or since this function is only used once, just compose functions in `Fission.Web.Types` instead of writing a new function

File: library/Fission/Internal/Orphanage/MultipartForm.hs [hunk 2]
```diff
@@ -15,9 +14,3 @@ instance HasSwagger api => HasSwagger (MultipartForm Mem (MultipartData Mem) :>
   toSwagger _ = Proxy @api
              |> toSwagger
              |> addConsumes ["multipart" // "form-data"]
-             |> addParam param
```
Comment (dholms) [inline library/Fission/Internal/Orphanage/MultipartForm.hs]: Just curious why we removed the param here. Seems like this route isn't very useful without an uploaded file param

**Comment by expede** [comment]
FYI I fixed some of the issues over at #220 -- double quotes and HTTPS prefixing in particular

File: library/Fission/Internal/Orphanage/MultipartForm.hs [hunk 3]
```diff
@@ -11,13 +11,17 @@ import Servant.Swagger.Internal
...
 
+
 instance HasSwagger api => HasSwagger (MultipartForm Mem (MultipartData Mem) :> api) where
   toSwagger _ = Proxy @api
-             |> toSwagger
-             |> addConsumes ["multipart" // "form-data"]
-             |> addParam param
+      |> toSwagger
+      |> addConsumes ["multipart" // "form-data"]
+      |> addParam param
```
Comment (expede) [inline library/Fission/Internal/Orphanage/MultipartForm.hs]: 💅

If we're going to move the pipelne to that position, let's also drop the `Proxy @api` to the next line as well. I would also say this in Elixir 😛

```haskell
  toSwagger _ =
    Proxy @api
      |> toSwagger
      |> addConsumes ["multipart" // "form-data"]
      |> addParam param
```

File: library/Fission/Internal/Orphanage/MultipartForm.hs [hunk 4]
```diff
@@ -11,13 +11,17 @@ import Servant.Swagger.Internal
...
       param = mempty
-           |> name        .~ "file"
-           |> description ?~ "A file to upload (may also be multipart/form-data)"
-           |> required    ?~ True
+        |> name .~ "file"
+        |> required ?~ True
+        |> description ?~ "A file to upload (may also be multipart/form-data)"
+        |> schema .~ ParamOther (mempty
+            |> in_ .~ ParamFormData
+            |> paramSchema .~ (mempty |> type_ ?~ SwaggerFile))
```
Comment (expede) [inline library/Fission/Internal/Orphanage/MultipartForm.hs]: Ooh, yeah, I'd break this out, too:

Option 1

```haskell
   where
      param = 
        mempty
          |> name .~ "file"
          |> description ?~ "A file to upload (may also be multipart/form-data)"
          |> required ?~ True
          |> schema .~ ParamOther (
               mempty
                 |> in_ .~ ParamFormData
                 |> paramSchema .~ (mempty |> type_ ?~ SwaggerFile)
          )
```

Option 2:

```haskell
   where
      param = mempty
        |> name .~ "file"
           |> description ?~ "A file to upload (may also be multipart/form-data)"
        |> required ?~ True
        |> description ?~ "A file to upload (may also be multipart/form-data)"
        |> schema .~ ParamOther paramSchema

      paramSchema = 
        mempty
          |> in_ .~ ParamFormData
          |> paramSchema .~ fileType

      fileType = 
        mempty |> type_ ?~ SwaggerFile
```

File: library/Fission/Internal/UTF8.hs [hunk 5]
```diff
@@ -14,9 +14,9 @@ module Fission.Internal.UTF8
 
 import           Flow
 import           RIO
-import qualified RIO.ByteString      as Strict
-import qualified RIO.ByteString.Lazy as Lazy
-import qualified RIO.Text            as Text
+import qualified RIO.ByteString             as Strict
+import qualified RIO.ByteString.Lazy        as Lazy
+import qualified RIO.Text                   as Text
```
Comment (expede) [inline library/Fission/Internal/UTF8.hs]: Why?

File: library/Fission/Web/Swagger.hs [hunk 6]
```diff
@@ -39,10 +38,10 @@ docs host' =
     |> user
 
 app :: HasSwagger api => Proxy api -> Web.Host -> Swagger
-app proxy (Web.Host (BaseUrl { baseUrlHost })) =
+app proxy appHost =
   proxy
     |> toSwagger
-    |> host               ?~ Host baseUrlHost Nothing
+    |> host               ?~ Host (Web.getHostName appHost) Nothing
```
Comment (expede) [inline library/Fission/Web/Swagger.hs]: Does that unwrap deeply enough?

EDIT

Oh, I see. There's a helper function. That confused me on first pass, becasue the name is so similar. I'm not sure if `master` changed under you (uses pattern matching) 🤔 Another version could be:

```haskell
host ?~ Host (appHost |> Web.getHostName |> baseUrlHost) Nothing
```

or rename

```haskell
getRawHost :: Host -> String
```

File: library/Fission/Web/Types.hs [hunk 7]
```diff
@@ -17,7 +19,7 @@ newtype Host = Host { getHost :: BaseUrl }
                    )
 
 instance Show Host where
-  show = show . UTF8.stripNBS 1 . encode
+  show = Char8.unpack . UTF8.stripNBS 1 . encode
```
Comment (expede) [inline library/Fission/Web/Types.hs]: These may be equivalent 🤔

Comment (expede) [reply library/Fission/Web/Types.hs]: Whatever, they do the same thing 👍 No need to change your PR

File: library/Fission/Internal/UTF8.hs (hunk 5 above)
Comment (bechurch) [reply library/Fission/Internal/UTF8.hs]: Oh, I believe I had aligned them with a longer import I later removed.

**Comment by bechurch** [comment]
@expede Updated with your suggestions
